# Generated by Django 5.1.7 on 2025-07-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assethistory_asset'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations_made', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
