# Generated by Django 5.1.7 on 2025-07-31 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetallocation_allocated_by_and_more'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='users.profile'),
        ),
    ]
