# Generated by Django 5.1.7 on 2025-08-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetrequest_requester'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_held_assets', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='allocated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_event_history', to='users.profile'),
        ),
    ]
