# Generated by Django 5.1.7 on 2025-08-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_current_holder_and_more'),
        ('institution', '0022_branch_is_active_department_is_active_and_more'),
        ('users', '0007_permission_is_active_permissioncategory_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_serial_batch',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetreturn',
            name='is_active',
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='alloc_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='request_reference_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'serial_number', 'batch_number'), name='unique_asset_serial_batch'),
        ),
        migrations.AddConstraint(
            model_name='assetallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('alloc_code',), name='unique_active_alloc_code'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'category_name'), name='unique_active_category_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='assetrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('request_reference_code',), name='unique_active_request_reference_code'),
        ),
    ]
