# Generated by Django 5.1.7 on 2025-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_current_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
