# Generated by Django 5.1.7 on 2025-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetcategory_code'),
        ('assets', '0007_asset_is_active_assetallocation_is_active_and_more'),
    ]

    operations = [
    ]
