# Generated by Django 5.1.7 on 2025-08-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_merge_20250812_1259'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetrequest',
            name='unique_active_request_reference_code',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='is_active',
        ),
    ]
