# Generated by Django 5.1.7 on 2025-08-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_assetrequest_unique_active_request_reference_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_serial_batch',
        ),
        migrations.RemoveConstraint(
            model_name='assetallocation',
            name='unique_active_alloc_code',
        ),
        migrations.RemoveConstraint(
            model_name='assetcategory',
            name='unique_active_category_per_institution',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetreturn',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assetreturn',
            name='is_active',
        ),
    ]
