# Generated by Django 5.1.7 on 2025-08-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_deleted_at_asset_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
