# Generated by Django 5.1.7 on 2025-08-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_deleted_at_asset_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_asset_serial_batch',
        ),
    ]
