# Generated by Django 5.1.7 on 2025-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_remove_asset_unique_asset_serial_batch'),
        ('institution', '0039_alter_department_institution'),
        ('users', '0009_customuser_deleted_at_permission_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'serial_number', 'batch_number'), name='unique_asset_serial_batch'),
        ),
    ]
