# Generated by Django 5.1.7 on 2025-08-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_asset_unique_asset_serial_batch'),
        ('assets', '0014_assetallocation_approval_status_and_more'),
    ]

    operations = [
    ]
