# Generated by Django 5.1.7 on 2025-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_updated_by_assetallocation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_request_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
    ]
