# Generated by Django 5.1.7 on 2025-07-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tasktimesheet',
            name='projects_ta_task_id_77fbc0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tasktimesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='led_tasks', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tasktimesheet',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='projects.task'),
        ),
        migrations.RemoveField(
            model_name='tasktimesheet',
            name='user',
        ),
    ]
