# Generated by Django 5.1.7 on 2025-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_tasktimesheet_projects_ta_task_id_77fbc0_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskdocument',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tasktimesheet',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasktimesheet',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
