# Generated by Django 5.1.7 on 2025-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimesheet',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktimesheet',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
