# Generated by Django 5.1.7 on 2025-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_is_active_projectdocument_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktimesheet',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
