# Generated by Django 5.1.7 on 2025-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0066_child_created_by_child_updated_by_and_more'),
        ('projects', '0010_project_completion_date_task_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='leaders',
        ),
        migrations.AddField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(related_name='project_members', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='led_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='led_tasks', to='employee.employee'),
        ),
    ]
