# Generated by Django 5.2.3 on 2025-06-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(help_text='Lower number = first to approve')),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowaction')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('Institution', 'action', 'level')},
            },
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowcategory'),
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], default='not_started', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tasks', to='users.profile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.institutionapprovalstep')),
            ],
            options={
                'unique_together': {('step', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionApprovalStepApprovorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workflows.institutionapprovalstep')),
            ],
            options={
                'unique_together': {('step', 'approver_role')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionApprovalStepApprovorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='workflows.institutionapprovalstep')),
            ],
            options={
                'unique_together': {('step', 'approver_user')},
            },
        ),
    ]
