# Generated by Django 5.1.7 on 2025-07-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institution_zoom_account_id_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionapprovalstep',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='institutionapprovalstep',
            unique_together={('institution', 'action', 'level')},
        ),
    ]
