# Generated by Django 5.1.7 on 2025-08-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_rename_institution_institutionapprovalstep_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionapprovalstep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
