# Generated by Django 5.1.7 on 2025-09-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_institutionapprovalstep_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionapprovalstepapprovoruser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='institutionapprovalstepapprovoruser',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='institutionapprovalstepapprovoruser',
            name='step',
        ),
        migrations.DeleteModel(
            name='ApprovalTask',
        ),
        migrations.DeleteModel(
            name='InstitutionApprovalStepApprovorUser',
        ),
    ]
