# Generated by Django 5.1.7 on 2025-09-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_institutionapprovalstepapprovoruser_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionApprovalStepApprovorRole',
        ),
    ]
