# Generated by Django 5.1.7 on 2025-09-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_delete_institutionapprovalstepapprovorrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowaction',
            name='category',
        ),
        migrations.DeleteModel(
            name='InstitutionApprovalStep',
        ),
        migrations.DeleteModel(
            name='WorkflowAction',
        ),
        migrations.DeleteModel(
            name='WorkflowCategory',
        ),
    ]
