# Generated by Django 5.1.7 on 2025-07-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_system'),
        ('leave_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='institution.institution'),
            preserve_default=False,
        ),
    ]
