# Generated by Django 5.1.7 on 2025-07-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_system'),
        ('leave_mgt', '0002_leaveapplication_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='institution.institution'),
        ),
    ]
