# Generated by Django 5.1.7 on 2025-07-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_system'),
        ('leave_mgt', '0003_alter_leavebalance_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='institution.institution'),
            preserve_default=False,
        ),
    ]
