# Generated by Django 5.1.7 on 2025-07-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0004_alter_leavebalance_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='max_carry_forward_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
