# Generated by Django 5.1.7 on 2025-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0005_alter_leavetype_max_carry_forward_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether leave application should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether leave balance should be treated as active or in active'),
        ),
    ]
