# Generated by Django 5.1.7 on 2025-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0006_leaveapplication_is_active_leavebalance_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='is_active',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
