# Generated by Django 5.1.7 on 2025-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employee_options_remove_employee_is_active_and_more'),
        ('institution', '0023_remove_branch_is_active_remove_department_is_active_and_more'),
        ('leave_mgt', '0007_remove_leaveapplication_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'leave_type', 'year'), name='unique_active_leave_type_per_year_per_employee'),
        ),
    ]
