# Generated by Django 5.1.7 on 2025-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0029_institutionworkingdays_deleted_at_and_more'),
        ('leave_mgt', '0009_leaveapplication_is_active_leavebalance_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('leave_type', 'institution'), name='unique_active_leave_policy_per_type_institution'),
        ),
    ]
