# Generated by Django 5.1.7 on 2025-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0010_leavepolicy_unique_active_leave_policy_per_type_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
