# Generated by Django 5.1.7 on 2025-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgt', '0012_leaveapplication_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
