# Generated by Django 5.1.7 on 2025-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_until',
            field=models.DateField(blank=True, help_text='If frequency is set, event will repeat until this date', null=True),
        ),
    ]
