# Generated by Django 5.1.7 on 2025-07-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0002_event_frequency_event_repeat_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_occurrences', to='calendar2.calendar')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar2.event')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('event', 'date')},
            },
        ),
    ]
