# Generated by Django 5.1.7 on 2025-07-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0003_eventoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='physical', max_length=20),
        ),
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('join_url', models.URLField()),
                ('start_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_event_details', to='calendar2.event')),
            ],
        ),
    ]
