# Generated by Django 5.1.7 on 2025-09-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0006_calendar_approval_status_event_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='approval_status',
        ),
    ]
