# Generated by Django 5.1.7 on 2025-09-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0008_calendar_created_by_calendar_updated_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineMeeting',
        ),
    ]
