# Generated by Django 5.1.7 on 2025-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0009_delete_onlinemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_birthday',
            field=models.BooleanField(default=False),
        ),
    ]
