# Generated by Django 5.1.7 on 2025-10-15 11:08

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('calendar2', '0011_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
