# Generated by Django 5.1.7 on 2025-07-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0008_institution_system'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('target_audience', models.CharField(choices=[('all', 'All Employees'), ('department', 'Specific Department'), ('individual', 'Specific Individual'), ('specific_employees', 'Specific Employees')], default='all', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_events', to='institution.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_events', to='institution.institution')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_employees_events', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_public_holidays', to='institution.institution')),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
                'unique_together': {('institution', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_calendars', to='institution.institution')),
                ('events', models.ManyToManyField(blank=True, related_name='calendars', to='calender.event')),
                ('public_holidays', models.ManyToManyField(blank=True, related_name='calendars', to='calender.publicholiday')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'ordering': ['-year', 'created_at'],
                'unique_together': {('institution', 'year')},
            },
        ),
    ]
