# Generated by Django 5.1.7 on 2025-08-29 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0031_institutionkycdocument_delete_institutiondocument'),
        ('users', '0009_customuser_deleted_at_permission_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actions', models.ManyToManyField(blank=True, related_name='approval_documents', to='approval.action')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.action')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDocumentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocument')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ApproverGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDocumentLevelOverriders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_document_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel')),
                ('approver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup')),
            ],
            options={
                'verbose_name': 'Approval Document Level Overrider',
                'verbose_name_plural': 'Approval Document Level Overriders',
                'unique_together': {('approval_document_level', 'approver_group')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocumentLevelApprovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_document_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel')),
                ('approver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup')),
            ],
            options={
                'verbose_name': 'Approval Document Level Approver',
                'verbose_name_plural': 'Approval Document Level Approvers',
                'unique_together': {('approval_document_level', 'approver_group')},
            },
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='approvers',
            field=models.ManyToManyField(related_name='approver_levels', through='approval.ApprovalDocumentLevelApprovers', to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='overriders',
            field=models.ManyToManyField(related_name='overrider_levels', through='approval.ApprovalDocumentLevelOverriders', to='approval.approvergroup'),
        ),
        migrations.CreateModel(
            name='ApproverGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, through='approval.ApproverGroupRole', to='users.role'),
        ),
        migrations.CreateModel(
            name='ApproverGroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='users',
            field=models.ManyToManyField(blank=True, through='approval.ApproverGroupUser', to='users.profile'),
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('terminated', 'Terminated')], default='not_started', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='approval.approval')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel')),
            ],
            options={
                'ordering': ['level__level'],
                'unique_together': {('approval', 'level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentlevel',
            unique_together={('approval_document', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='approvergroup',
            unique_together={('institution', 'name')},
        ),
    ]
