# Generated by Django 5.1.7 on 2025-08-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_approvergroupuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocumentlevel',
            name='approval_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='approval.approvaldocument'),
        ),
    ]
