# Generated by Django 5.1.7 on 2025-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_alter_approvaldocumentlevel_approval_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocumentlevel',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
