# Generated by Django 5.1.7 on 2025-09-04 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_alter_approvaldocumentlevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
