# Generated by Django 5.1.7 on 2025-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_approvaldocumentlevel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('terminated', 'Terminated'), ('overridden', 'Overridden')], default='not_started', max_length=20),
        ),
    ]
