# Generated by Django 5.1.7 on 2025-09-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_action_created_by_action_updated_by_and_more'),
        ('users', '0014_signature_approval_status_signature_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvaldocumentlevelapprovers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentleveloverriders',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='approver_users',
            field=models.ManyToManyField(blank=True, related_name='approver_users_levels', through='approval.ApprovalDocumentLevelApprovers', to='users.profile'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='overrider_users',
            field=models.ManyToManyField(blank=True, related_name='overrider_users_levels', through='approval.ApprovalDocumentLevelOverriders', to='users.profile'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevelapprovers',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='approvaldocumentleveloverriders',
            name='overrider_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='approvaldocumentlevelapprovers',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentlevelapprovers',
            unique_together={('approval_document_level', 'approver_group', 'approver_user')},
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentleveloverriders',
            unique_together={('approval_document_level', 'approver_group', 'overrider_user')},
        ),
    ]
