# Generated by Django 5.1.7 on 2025-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_alter_approvaldocumentlevelapprovers_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocumentlevel',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approver_levels', through='approval.ApprovalDocumentLevelApprovers', to='approval.approvergroup'),
        ),
        migrations.AlterField(
            model_name='approvaldocumentlevel',
            name='overriders',
            field=models.ManyToManyField(blank=True, related_name='overrider_levels', through='approval.ApprovalDocumentLevelOverriders', to='approval.approvergroup'),
        ),
    ]
