# Generated by Django 5.1.7 on 2025-09-28 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0009_alter_approvaldocumentlevel_approvers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvaldocumentleveloverriders",
            name="approver_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="approval.approvergroup",
            ),
        ),
    ]
