# Generated by Django 5.1.7 on 2025-07-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='institution',
        ),
    ]
