# Generated by Django 5.1.7 on 2025-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_systemconfiguration_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_code', models.CharField(max_length=10, unique=True)),
                ('day_name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
