# Generated by Django 5.1.7 on 2025-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemday'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
