# Generated by Django 5.1.7 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_systemconfiguration_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
