# Generated by Django 5.1.7 on 2025-08-13 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_systemconfiguration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
