# Generated by Django 5.1.7 on 2025-09-16 10:35

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0043_remove_institution_zoom_account_id_and_more'),
        ('settings', '0008_meetingintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingintegration',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_integrations', to='institution.institution'),
        ),
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('provider', models.CharField(choices=[('cpanel', 'cPanel'), ('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365')], default='cpanel', max_length=20)),
                ('domain', models.CharField(help_text='e.g., example.com', max_length=100)),
                ('format_template', models.CharField(default='{first_name}.{last_name}', help_text='Use placeholders like {first_name}, {last_name}, {initials}, {fullname} (lowercased and sanitized)', max_length=255)),
                ('api_url', models.URLField(blank=True, help_text='For cPanel: e.g., https://yourserver.com:2087', null=True)),
                ('api_username', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_config', to='institution.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
