# Generated by Django 5.1.7 on 2025-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_meetingintegration_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='port',
            field=models.CharField(default='2083', help_text='API port (e.g., 2083 for cPanel HTTPS)', max_length=5),
        ),
        migrations.AlterField(
            model_name='emailproviderconfig',
            name='api_url',
            field=models.URLField(blank=True, help_text='For cPanel: e.g., https://yourserver.com:2083', null=True),
        ),
    ]
