# Generated by Django 5.1.7 on 2025-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_emailproviderconfig_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Admin email for Google Workspace delegation (e.g., admin@yourdomain.com)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailproviderconfig',
            name='quota',
            field=models.PositiveIntegerField(default=500, help_text='Email quota in MB (applies to cPanel; Google Workspace quotas are managed via Admin Console)'),
        ),
    ]
