# Generated by Django 5.1.7 on 2025-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_emailproviderconfig_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailproviderconfig',
            name='webmail_url',
            field=models.URLField(blank=True, help_text='Webmail login URL (e.g., https://mail.yourdomain.com for cPanel or https://mail.google.com for Google Workspace)', null=True),
        ),
    ]
