# Generated by Django 5.1.7 on 2025-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceemployeeattachment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
