# Generated by Django 5.1.7 on 2025-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_deviceemployeeattachment_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceemployeeattachment",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
    ]
