# Generated by Django 5.1.7 on 2025-10-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_deviceemployeeattachment_is_synced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceemployeeattachment",
            name="enroll_id",
        ),
    ]
