# Generated by Django 5.1.7 on 2025-10-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_remove_deviceemployeeattachment_enroll_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceemployeeattachment",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_employee_attachments",
                to="devices.device",
            ),
        ),
    ]
