# Generated by Django 5.1.7 on 2025-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_deviceemployeeattachment_device"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deviceemployeeattachment",
            old_name="employee",
            new_name="employee_id",
        ),
    ]
