# Generated by Django 5.1.7 on 2025-10-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_rename_employee_deviceemployeeattachment_employee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deviceemployeeattachment",
            old_name="employee_id",
            new_name="employee",
        ),
    ]
