# Generated by Django 5.1.7 on 2025-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_rename_employee_id_deviceemployeeattachment_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
