# Generated by Django 5.1.7 on 2025-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_connection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
