# Generated by Django 5.1.7 on 2025-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_acknowledgment_acknowledged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgment',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
