# Generated by Django 5.1.7 on 2025-09-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_acknowledgment_acknowledged_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='approval_status',
        ),
    ]
