# Generated by Django 5.1.7 on 2025-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_announcement_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
