# Generated by Django 5.1.7 on 2025-10-01 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_announcement_approval_status'),
        ('employee', '0078_alter_employeecompanyemail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acknowledgment',
            new_name='EmployeeAnnouncementAcknowledgment',
        ),
    ]
