# Generated by Django 5.1.7 on 2025-10-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_employees',
        ),
    ]
