# Generated by Django 5.1.7 on 2025-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_remove_announcement_target_employees'),
        ('employee', '0078_alter_employeecompanyemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_employees',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', through='communication.EmployeeAnnouncementAcknowledgment', to='employee.employee'),
        ),
    ]
