# Generated by Django 5.2.3 on 2025-06-11 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_location', models.CharField(max_length=255)),
                ('branch_latitude', models.FloatField(blank=True, null=True)),
                ('branch_longitude', models.FloatField(blank=True, null=True)),
                ('branch_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('branch_opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('branch_closing_time', models.TimeField(default=datetime.time(23, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('first_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institutions/images/')),
                ('theme_color', models.CharField(blank=True, max_length=400, null=True)),
                ('setup', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='approved', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='institutions/documents/')),
                ('document_type', models.CharField(blank=True, max_length=10, null=True)),
                ('document_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Document',
                'verbose_name_plural': 'Shop Documents',
            },
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Branch',
                'verbose_name_plural': 'User Branches',
            },
        ),
    ]
