# Generated by Django 5.2.3 on 2025-06-13 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('institution_owner', 'institution_name')},
        ),
    ]
