# Generated by Django 5.1.7 on 2025-06-19 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_employee_address_and_more'),
        ('institution', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_head', to='employee.employee'),
        ),
    ]
