# Generated by Django 5.1.7 on 2025-06-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_department_head_of_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
    ]
