# Generated by Django 5.1.7 on 2025-07-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_userbranch_unique_default_branch_per_user"),
        ("users", "0003_systemtype_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.system",
            ),
        ),
    ]
