# Generated by Django 5.1.7 on 2025-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institution_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
