# Generated by Django 5.1.7 on 2025-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_institution_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='zoom_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='zoom_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='zoom_client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
