# Generated by Django 5.1.7 on 2025-07-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institution_zoom_account_id_and_more'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='default_employee_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_employee_role', to='users.role'),
        ),
    ]
