# Generated by Django 5.1.7 on 2025-07-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_alter_institution_default_employee_role'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='default_employee_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_role', to='users.role'),
        ),
    ]
