# Generated by Django 5.1.7 on 2025-08-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0015_institutionbankaccount_branch_paying_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='paying_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_branches', to='institution.institutionbankaccount'),
        ),
    ]
