# Generated by Django 5.1.7 on 2025-08-05 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0016_alter_branch_paying_bank_account'),
        ('settings', '0003_systemday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_institution_working_days', to=settings.AUTH_USER_MODEL)),
                ('days', models.ManyToManyField(blank=True, related_name='working_days', to='settings.systemday')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='institution.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_institution_working_days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
