# Generated by Django 5.1.7 on 2025-08-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0017_institutionworkingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionworkingdays',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='institution.institution'),
        ),
    ]
