# Generated by Django 5.1.7 on 2025-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0018_alter_institutionworkingdays_institution'),
        ('settings', '0003_systemday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionworkingdays',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='working_day', to='settings.systemday'),
        ),
    ]
