# Generated by Django 5.1.7 on 2025-08-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_alter_institutionworkingdays_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_taxes', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='institution.institution')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_taxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Tax',
                'verbose_name_plural': 'Institution Taxes',
            },
        ),
        migrations.CreateModel(
            name='InstitutionTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rule_name', models.CharField(max_length=100)),
                ('tax_rule_description', models.TextField(blank=True, null=True)),
                ('tax_rule_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_rule_fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tax_rules', to=settings.AUTH_USER_MODEL)),
                ('institution_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='institution.institutiontax')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_tax_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
