# Generated by Django 5.1.7 on 2025-08-07 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0020_institutiontax_institutiontaxrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiontax',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_taxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutiontax',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_taxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
