# Generated by Django 5.1.7 on 2025-08-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0021_alter_institutiontax_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the branch should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether department should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the institution should be active or in active'),
        ),
        migrations.AddField(
            model_name='institutionbankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether institution bank account should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='institutionbanktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the institution bank type should be treated active or in active. '),
        ),
        migrations.AddField(
            model_name='institutiontax',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether institution type should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='institutiontaxrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether institution tax rule should be treated as active or in active'),
        ),
        migrations.AddField(
            model_name='userbranch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether user branch should be treated as active or in active.'),
        ),
    ]
