# Generated by Django 5.1.7 on 2025-08-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_branch_is_active_department_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionbankaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionbanktype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutiontax',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutiontaxrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userbranch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='branch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbankaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbanktype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutiontax',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutiontaxrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
