# Generated by Django 5.1.7 on 2025-08-12 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_remove_branch_is_active_remove_department_is_active_and_more'),
        ('users', '0008_alter_role_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution_owner', 'institution_name'), name='unique_active_institution_name_per_institution_owner'),
        ),
        migrations.AddConstraint(
            model_name='institutionbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution_bank', 'account_number'), name='unique_active_account_number_per_instititution_bank'),
        ),
    ]
