# Generated by Django 5.1.7 on 2025-08-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0025_branch_is_active_department_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='institution',
            name='unique_active_institution_name_per_institution_owner',
        ),
        migrations.RemoveConstraint(
            model_name='institutionbankaccount',
            name='unique_active_account_number_per_instititution_bank',
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='institutionbankaccount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionbanktype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutionbanktype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutiontax',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutiontax',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutiontaxrule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutiontaxrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionbankaccount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutionbankaccount',
            name='is_active',
        ),
    ]
