# Generated by Django 5.1.7 on 2025-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0027_branch_deleted_at_branch_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_attendance_penalties_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
