# Generated by Django 5.1.7 on 2025-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0028_institution_is_attendance_penalties_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionworkingdays',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionworkingdays',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
