# Generated by Django 5.1.7 on 2025-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0029_institutionworkingdays_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='user_inactivity_time',
            field=models.PositiveIntegerField(default=15, help_text='User inactivity time in minutes before automatic logout'),
        ),
    ]
