# Generated by Django 5.1.7 on 2025-08-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0030_institution_user_inactivity_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutiondocument',
            options={'verbose_name': 'Institution Document', 'verbose_name_plural': 'Institution Documents'},
        ),
    ]
