# Generated by Django 5.2 on 2025-08-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0030_institution_user_inactivity_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionKYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_title", models.CharField(max_length=255)),
                (
                    "document_file",
                    models.FileField(upload_to="institutions/kyc/documents/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution KYC Document",
                "verbose_name_plural": "Institution KYC Documents",
            },
        ),
        migrations.DeleteModel(
            name="InstitutionDocument",
        ),
    ]
