# Generated by Django 5.1.7 on 2025-08-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0031_institutionkycdocument_delete_institutiondocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('penalty_type', models.CharField(choices=[('late_coming', 'Late Coming'), ('early_leaving', 'Early Leaving'), ('absent', 'Absent'), ('no_response_spotcheck', 'No Response for Spotcheck'), ('late_spotcheck_response', 'Late Spotcheck Response')], max_length=50)),
                ('penalty_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalty_value_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=20, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_configs', to='institution.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_penalty_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionPenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('penalty_type', models.CharField(choices=[('late_coming', 'Late Coming'), ('early_leaving', 'Early Leaving'), ('absent', 'Absent'), ('no_response_spotcheck', 'No Response for Spotcheck'), ('late_spotcheck_response', 'Late Spotcheck Response')], default='late_coming', max_length=50)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('penalty_value_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=50)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_config', to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
