# Generated by Django 5.1.7 on 2025-08-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0031_alter_institutiondocument_options'),
        ('institution', '0031_institutionkycdocument_delete_institutiondocument'),
    ]

    operations = [
    ]
