# Generated by Django 5.1.7 on 2025-08-29 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0032_branchpenaltyconfig_institutionpenaltyconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchpenaltyconfig',
            name='created_by',
        ),
        migrations.AddField(
            model_name='branchpenaltyconfig',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="Percentage value when penalty_value_type is 'percentage'", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='institutionpenaltyconfig',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="Percentage value when penalty_value_type is 'percentage'", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='branchpenaltyconfig',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='branchpenaltyconfig',
            name='penalty_value_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutionpenaltyconfig',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='institutionpenaltyconfig',
            name='penalty_value_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], default='fixed', max_length=50),
        ),
    ]
