# Generated by Django 5.2 on 2025-08-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0033_remove_branchpenaltyconfig_created_by_and_more"),
        ("settings", "0006_systemconfiguration_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[("REMOTE", "Remote"), ("PHYSICAL", "Physical")],
                        default="PHYSICAL",
                        max_length=255,
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.systemday",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchWorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_days",
                        to="institution.branch",
                    ),
                ),
                (
                    "days",
                    models.ManyToManyField(
                        related_name="branch_working_days",
                        through="institution.BranchDay",
                        to="settings.systemday",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="branchday",
            name="branch_working_days",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_days",
                to="institution.branchworkingdays",
            ),
        ),
        migrations.CreateModel(
            name="BranchShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="institution.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "name")},
            },
        ),
    ]
