# Generated by Django 5.1.7 on 2025-08-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0033_remove_branchpenaltyconfig_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionpenaltyconfig',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_config', to='institution.institution'),
        ),
    ]
