# Generated by Django 5.1.7 on 2025-08-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0034_alter_institutionpenaltyconfig_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocationComaparisonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('radius_in_meters', models.IntegerField(default=100)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_comparison_settings', to='institution.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
