# Generated by Django 5.2 on 2025-08-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0034_branchday_branchworkingdays_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchshift",
            options={"ordering": ("shift_day__day__level", "name")},
        ),
        migrations.AddField(
            model_name="branchshift",
            name="shift_day",
            field=models.ForeignKey(
                blank=True,
                help_text="The day this shift occurs",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="institution.branchday",
            ),
        ),
    ]
