# Generated by Django 5.2 on 2025-08-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0035_alter_branchshift_options_branchshift_shift_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchday",
            options={"ordering": ("day__level",)},
        ),
    ]
