# Generated by Django 5.1.7 on 2025-08-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0035_branchlocationcomaparisonconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchLocationComaparisonConfig',
            new_name='BranchLocationComparisonConfig',
        ),
    ]
