# Generated by Django 5.1.7 on 2025-08-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0035_branchlocationcomaparisonconfig'),
        ('institution', '0036_alter_branchday_options'),
    ]

    operations = [
    ]
