# Generated by Django 5.1.7 on 2025-08-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0036_rename_branchlocationcomaparisonconfig_branchlocationcomparisonconfig'),
        ('institution', '0037_merge_20250829_1830'),
    ]

    operations = [
    ]
