# Generated by Django 5.1.7 on 2025-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0040_branch_approval_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branchpenaltyconfig',
            constraint=models.UniqueConstraint(fields=('branch', 'penalty_type'), name='unique_branch_penalty_type'),
        ),
        migrations.AddConstraint(
            model_name='institutionpenaltyconfig',
            constraint=models.UniqueConstraint(fields=('institution', 'penalty_type'), name='unique_institution_penalty_type'),
        ),
    ]
