# Generated by Django 5.1.7 on 2025-09-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0042_branch_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='zoom_account_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='zoom_client_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='zoom_client_secret',
        ),
    ]
