# Generated by Django 5.1.7 on 2025-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0044_alter_department_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiontaxrule',
            name='tax_rule_formula',
            field=models.TextField(blank=True, help_text="Formula for tax calculation (e.g., '(taxable_gross_salary - 235000) * 0.10' or '(gross_salary - 410000) * 0.30 + 25000')", null=True),
        ),
        migrations.AddField(
            model_name='institutiontaxrule',
            name='taxable_income_source',
            field=models.CharField(blank=True, choices=[('taxable_gross_salary', 'Taxable Gross Salary'), ('gross_salary', 'Gross Salary'), ('basic_salary', 'Basic Salary')], help_text='Field from payslip to use as the taxable income base in the formula', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institutiontaxrule',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lower bound of the taxable income range (in UGX)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='institutiontaxrule',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of the taxable income range (in UGX, leave null for open-ended upper limit)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='institutiontaxrule',
            name='tax_rule_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed tax amount (in UGX) if not using percentage or formula', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='institutiontaxrule',
            name='tax_rule_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage rate for tax calculation (e.g., 10.00 for 10%)', max_digits=5, null=True),
        ),
    ]
