# Generated by Django 5.1.7 on 2025-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0046_taxrulecategory_institutiontaxrule_tax_rule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
