# Generated by Django 5.1.7 on 2025-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0047_institution_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrulecategory',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
