# Generated by Django 5.1.7 on 2025-10-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0048_taxrulecategory_code'),
        ('settings', '0012_emailproviderconfig_webmail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchday',
            name='closing_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='branchday',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.CreateModel(
            name='InstitutionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='09:00:00')),
                ('closing_time', models.TimeField(default='17:00:00')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.systemday')),
                ('institution_working_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_days', to='institution.institutionworkingdays')),
            ],
            options={
                'ordering': ('day__level',),
            },
        ),
        migrations.AddField(
            model_name='institutionworkingdays',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='working_days', through='institution.InstitutionDay', to='settings.systemday'),
        ),
    ]
