# Generated by Django 5.1.7 on 2025-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0049_branchday_closing_time_branchday_opening_time_and_more'),
        ('settings', '0012_emailproviderconfig_webmail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionworkingdays',
            name='days',
        ),
        migrations.AlterField(
            model_name='institutionworkingdays',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='working_day', through='institution.InstitutionDay', to='settings.systemday'),
        ),
    ]
