# Generated by Django 5.1.7 on 2025-10-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0050_remove_institutionworkingdays_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionworkingdays',
            old_name='day',
            new_name='days',
        ),
    ]
