# Generated by Django 5.1.7 on 2025-06-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='recruitment.jobadvertapplication'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('issued_contract', 'Issued Contract'), ('declined_offer', 'Declined Offer'), ('accepted_offer', 'Accepted Offer')], default='training', max_length=20),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
