# Generated by Django 5.1.7 on 2025-07-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_merge_20250725_1035'),
        ('institution', '0010_institution_zoom_account_id_and_more'),
        ('onboarding', '0003_alter_onboarding_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionEmployeeSeparationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('contract_end', 'Contract End'), ('other', 'Other')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_types', to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSeparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('separation_status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separations', to='employee.employee')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separation_initiated_by', to='employee.employee')),
                ('employee_separation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_separations', to='onboarding.institutionemployeeseparationtypes')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSeparationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='separation_policies/')),
                ('description', models.TextField(blank=True, null=True)),
                ('min_notice_days', models.IntegerField(default=30)),
                ('max_notice_days', models.IntegerField(default=90)),
                ('require_separation_letter', models.BooleanField(default=False)),
                ('require_all_stages', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('enforce_policy', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('separation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_policy', to='onboarding.institutionemployeeseparationtypes')),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('stage_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_stages', to='institution.institution')),
            ],
            options={
                'unique_together': {('institution', 'stage_name')},
            },
        ),
        migrations.AddField(
            model_name='institutionemployeeseparationtypes',
            name='supported_stages',
            field=models.ManyToManyField(blank=True, related_name='supported_separation_types', to='onboarding.offboardingstage'),
        ),
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_letter', models.FileField(blank=True, null=True, upload_to='resignation_letters/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('separation', models.OneToOneField(limit_choices_to={'employee_separation_type__category': 'resignation'}, on_delete=django.db.models.deletion.CASCADE, related_name='resignation_requests', to='onboarding.employeeseparation')),
            ],
        ),
        migrations.CreateModel(
            name='RetirementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirement_letter', models.FileField(blank=True, null=True, upload_to='retirement_letters/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('separation', models.OneToOneField(limit_choices_to={'employee_separation_type__category': 'retirement'}, on_delete=django.db.models.deletion.CASCADE, related_name='retirement_request', to='onboarding.employeeseparation')),
            ],
        ),
        migrations.CreateModel(
            name='SeparationStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('separation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='onboarding.employeeseparation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_progress', to='onboarding.offboardingstage')),
            ],
        ),
        migrations.CreateModel(
            name='TerminationInitiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_letter', models.FileField(blank=True, null=True, upload_to='termination_letters/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('initiation_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('separation', models.OneToOneField(limit_choices_to={'employee_separation_type__category': 'termination'}, on_delete=django.db.models.deletion.CASCADE, related_name='termination_initiation', to='onboarding.employeeseparation')),
            ],
        ),
    ]
