# Generated by Django 5.1.7 on 2025-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_institutionemployeeseparationtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('training', 'Training'), ('contract_review', 'Contract Review'), ('issued_contract', 'Issued Contract'), ('declined_offer', 'Declined Offer'), ('accepted_offer', 'Accepted Offer')], default='initial', max_length=20),
        ),
    ]
