# Generated by Django 5.1.7 on 2025-07-31 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionseparationpolicy',
            name='separation_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separation_policy', to='onboarding.institutionemployeeseparationtypes'),
        ),
    ]
