# Generated by Django 5.1.7 on 2025-07-31 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_institutionseparationpolicy_separation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionseparationpolicy',
            name='separation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_policy', to='onboarding.institutionemployeeseparationtypes'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionseparationpolicy',
            unique_together={('separation_type', 'is_active')},
        ),
    ]
