# Generated by Django 5.1.7 on 2025-07-31 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_institutionseparationpolicy_separation_type_and_more'),
        ('users', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeseparation',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separation_initiated_by', to='users.profile'),
        ),
    ]
