# Generated by Django 5.1.7 on 2025-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_alter_employeeseparation_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionseparationpolicy',
            name='policy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
