# Generated by Django 5.1.7 on 2025-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_institutionseparationpolicy_policy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationrequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether resignation request should be treated as active or in active. '),
        ),
        migrations.AddField(
            model_name='terminationinitiation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether termination of institution should be treated as active or in active.'),
        ),
    ]
