# Generated by Django 5.1.7 on 2025-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_resignationrequest_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionseparationpolicy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='institutionemployeeseparationtypes',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offboardingstage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resignationrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='terminationinitiation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='institutionemployeeseparationtypes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionseparationpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingstage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminationinitiation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='institutionseparationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('separation_type',), name='unique_active_separation_policy'),
        ),
        migrations.RemoveField(
            model_name='institutionseparationpolicy',
            name='is_active',
        ),
    ]
