# Generated by Django 5.1.7 on 2025-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_remove_branch_is_active_remove_department_is_active_and_more'),
        ('onboarding', '0011_alter_institutionseparationpolicy_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offboardingstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'stage_name'), name='unique_active_stage_name_per_institution'),
        ),
    ]
