# Generated by Django 5.1.7 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_offboardingstage_unique_active_stage_name_per_institution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='institutionseparationpolicy',
            name='unique_active_separation_policy',
        ),
        migrations.AddField(
            model_name='institutionemployeeseparationtypes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institutionseparationpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offboardingstage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terminationinitiation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='institutionseparationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('separation_type',), name='unique_active_separation_policy'),
        ),
    ]
