# Generated by Django 5.1.7 on 2025-08-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_remove_institutionseparationpolicy_unique_active_separation_policy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='institutionseparationpolicy',
            name='unique_active_separation_policy',
        ),
        migrations.RemoveConstraint(
            model_name='offboardingstage',
            name='unique_active_stage_name_per_institution',
        ),
        migrations.AlterUniqueTogether(
            name='offboardingstage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='institutionemployeeseparationtypes',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutionemployeeseparationtypes',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionseparationpolicy',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='institutionseparationpolicy',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resignationrequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='resignationrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='terminationinitiation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='terminationinitiation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offboardingstage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='offboardingstage',
            name='is_active',
        ),
    ]
