# Generated by Django 5.1.7 on 2025-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0026_remove_institution_unique_active_institution_name_per_institution_owner_and_more'),
        ('onboarding', '0014_remove_institutionseparationpolicy_unique_active_separation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionemployeeseparationtypes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionemployeeseparationtypes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institutionseparationpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionseparationpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offboardingstage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingstage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terminationinitiation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminationinitiation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='offboardingstage',
            unique_together={('institution', 'stage_name')},
        ),
        migrations.AddConstraint(
            model_name='institutionseparationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('separation_type',), name='unique_active_separation_policy'),
        ),
        migrations.AddConstraint(
            model_name='offboardingstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'stage_name'), name='unique_active_stage_name_per_institution'),
        ),
    ]
