# Generated by Django 5.1.7 on 2025-08-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_institutionemployeeseparationtypes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
