# Generated by Django 5.1.7 on 2025-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_institutionemployeeseparationtypes_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementrequest',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='retirementrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retirementrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
