# Generated by Django 5.1.7 on 2025-10-07 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0048_taxrulecategory_code'),
        ('onboarding', '0020_employeeseparation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingstage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='The order of this stage in the offboarding process (lower numbers come first).'),
        ),
        migrations.AddIndex(
            model_name='offboardingstage',
            index=models.Index(fields=['institution', 'position'], name='onboarding__institu_adf17f_idx'),
        ),
        migrations.AddConstraint(
            model_name='offboardingstage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('institution', 'position'), name='unique_active_position_per_institution'),
        ),
    ]
