# Generated by Django 5.1.7 on 2025-10-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_offboardingstage_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='separationstageprogress',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Custom position of this stage for the specific separation (overrides OffboardingStage.position).'),
        ),
    ]
