# Generated by Django 5.1.7 on 2025-10-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_separationstageprogress_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeparationStageProgress',
        ),
    ]
