# Generated by Django 5.1.7 on 2025-10-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0023_delete_separationstageprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetirementRequest',
        ),
    ]
