# Generated by Django 5.1.7 on 2025-10-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_delete_retirementrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminationInitiation',
        ),
    ]
