# Generated by Django 5.1.7 on 2025-10-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0026_delete_resignationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSeparation',
        ),
    ]
