# Generated by Django 5.1.7 on 2025-10-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0028_delete_institutionseparationpolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionEmployeeSeparationTypes',
        ),
    ]
