# Generated by Django 5.1.7 on 2025-10-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_delete_institutionemployeeseparationtypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffboardingStage',
        ),
    ]
