# Generated by Django 5.1.7 on 2025-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0031_offboarding_handoverreport_terminationstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationstage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
