# Generated by Django 5.1.7 on 2025-08-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancepolicy',
            name='is_active',
        ),
        migrations.AddField(
            model_name='performancepolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
