# Generated by Django 5.1.7 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_performancepolicy_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancepolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
