# Generated by Django 5.1.7 on 2025-09-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performancepolicy_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformancePolicy',
        ),
    ]
