# Generated by Django 5.1.7 on 2025-09-13 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("employee", "0066_child_created_by_child_updated_by_and_more"),
        ("institution", "0042_branch_updated_by_and_more"),
        ("performance", "0006_emmployeeobjectives_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusPointSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("under_creation", "Under Creation"),
                            ("under_update", "Under Update"),
                            ("under_deletion", "Under Deletion"),
                            ("active", "Active"),
                        ],
                        default="under_creation",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "applicable_for",
                    models.CharField(
                        choices=[("managers", "Managers"), ("members", "Members")],
                        max_length=255,
                    ),
                ),
                (
                    "bonus_for",
                    models.CharField(
                        choices=[("completing", "Completing"), ("closing", "Closing")],
                        max_length=255,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("condition_field", models.CharField(max_length=255)),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("=", "Equal"),
                            ("<", "Less than"),
                            (">", "Greater than"),
                            ("<=", "Less than or equal"),
                            (">=", "Greater than or equal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("condition_value", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": [
                                "period",
                                "objectives",
                                "employeeobjectives",
                                "keyresult",
                                "feedback360",
                                "employeebonuspoint",
                                "questiontemplate",
                                "meeting",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institution.institution",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeObjectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("under_creation", "Under Creation"),
                            ("under_update", "Under Update"),
                            ("under_deletion", "Under Deletion"),
                            ("active", "Active"),
                        ],
                        default="under_creation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("on_track", "On Track"),
                            ("closed", "Closed"),
                            ("at_risk", "At Risk"),
                            ("behind", "Behind"),
                        ],
                        default="not_started",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
                (
                    "key_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="performance.keyresult",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performance.objectives",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
