# Generated by Django 5.1.7 on 2025-09-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0007_bonuspointsettings_employeeobjectives"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeebonuspoint",
            name="points",
        ),
        migrations.AddField(
            model_name="employeebonuspoint",
            name="bonus_point_setting",
            field=models.ForeignKey(
                blank=True,
                help_text="The bonus point setting that triggered this award, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_bonus_points",
                to="performance.bonuspointsettings",
            ),
        ),
    ]
