# Generated by Django 5.1.7 on 2025-09-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0008_remove_employeebonuspoint_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectives",
            old_name="Institution",
            new_name="institution",
        ),
    ]
