# Generated by Django 5.1.7 on 2025-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_rename_institution_objectives_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
