# Generated by Django 5.1.7 on 2025-09-15 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_remove_emmployeeobjectives_key_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emmployeeobjectives',
            name='assignment_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 14, 32, 49, 675235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 14, 32, 49, 674466, tzinfo=datetime.timezone.utc)),
        ),
    ]
