# Generated by Django 5.1.7 on 2025-09-15 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_alter_emmployeeobjectives_assignment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emmployeeobjectives',
            name='assignment_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 14, 41, 51, 704335, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 14, 41, 51, 703463, tzinfo=datetime.timezone.utc)),
        ),
    ]
