# Generated by Django 5.1.7 on 2025-09-16 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0017_alter_emmployeeobjectives_assignment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emmployeeobjectives',
            name='assignment_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 16, 4, 53, 11, 281236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 16, 4, 53, 11, 280111, tzinfo=datetime.timezone.utc)),
        ),
    ]
