# Generated by Django 5.1.7 on 2025-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0023_remove_employeeobjectives_key_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeobjectives',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
