# Generated by Django 5.1.7 on 2025-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0024_employeeobjectives_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspointsettings',
            name='applicable_for',
            field=models.CharField(choices=[('managers', 'Managers'), ('assignees', 'Assignees')], max_length=255),
        ),
    ]
