# Generated by Django 5.1.7 on 2025-09-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employee', '0067_alter_employee_position_alter_employee_user_and_more'),
        ('institution', '0044_alter_department_institution_and_more'),
        ('performance', '0025_alter_bonuspointsettings_applicable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspointsettings',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['objectives', 'task', 'project']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bonuspointsettings',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='employeebonuspoint',
            name='bonus_point_setting',
            field=models.ForeignKey(blank=True, help_text='The bonus point setting that triggered this award, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_bonus_points', to='performance.bonuspointsettings'),
        ),
        migrations.AlterField(
            model_name='employeebonuspoint',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeebonuspoint',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.period'),
        ),
        migrations.AlterField(
            model_name='employeeobjectives',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeobjectives',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.objectives'),
        ),
        migrations.AlterField(
            model_name='feedback360',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='feedback360',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.period'),
        ),
        migrations.AlterField(
            model_name='feedback360',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='key_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.keyresult'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectivemanagers', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='period',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
