# Generated by Django 5.1.7 on 2025-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0025_alter_bonuspointsettings_applicable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectives',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
