# Generated by Django 5.1.7 on 2025-09-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0026_alter_bonuspointsettings_content_type_and_more'),
        ('performance', '0026_objectives_completion_date'),
    ]

    operations = [
    ]
