# Generated by Django 5.1.7 on 2025-09-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0027_merge_20250917_0857'),
        ('performance', '0027_merge_20250917_1008'),
    ]

    operations = [
    ]
