# Generated by Django 5.1.7 on 2025-09-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0028_merge_20250917_1518'),
        ('performance', '0028_merge_20250917_1537'),
    ]

    operations = [
    ]
