# Generated by Django 5.1.7 on 2025-07-28 10:43

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttype_created_at_documenttype_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('richtext', 'Text')], max_length=50)),
                ('file', models.FileField(upload_to='document_templates/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for the contract template (used if template_type is richtext)', null=True)),
                ('placeholders', models.JSONField(default=list, help_text="List of placeholders used in the template, e.g. ['{{employee_name}}', '{{date}}']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
        ),
    ]
