# Generated by Django 5.1.7 on 2025-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of placeholders used in the template, e.g. ['{{employee_name}}', '{{date}}']", null=True),
        ),
    ]
