# Generated by Django 5.1.7 on 2025-07-28 12:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documenttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for the contract template (used if template_type is richtext)', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(default=1, upload_to='document_templates/'),
            preserve_default=False,
        ),
    ]
