# Generated by Django 5.1.7 on 2025-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documenttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted or user-provided content for the template.', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document_templates/'),
        ),
    ]
