# Generated by Django 5.1.7 on 2025-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documenttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('text', 'Text')], max_length=50),
        ),
    ]
