# Generated by Django 5.1.7 on 2025-07-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documenttemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_values', models.JSONField(default=dict, help_text="Values for the placeholders defined in the template, e.g. {'employee_name': 'John Doe', 'date': '2023-10-01'}")),
                ('status', models.CharField(choices=[('penging', 'Pending'), ('in_review', 'In Review'), ('reviewed', 'Reviewed')], max_length=20)),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate')),
            ],
        ),
    ]
