# Generated by Django 5.1.7 on 2025-07-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('reviewed', 'Reviewed')], max_length=20),
        ),
    ]
