# Generated by Django 5.1.7 on 2025-07-30 09:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_documenttemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=dict, help_text='Structured content for the template (e.g., sections, formatting, placeholders).', null=True),
        ),
    ]
