# Generated by Django 5.1.7 on 2025-07-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_documenttemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Structured content for the template (e.g., sections, formatting, placeholders).', null=True),
        ),
    ]
