# Generated by Django 5.1.7 on 2025-07-30 15:13

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_documenttemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown content for the template with formatting and placeholders (e.g., {{caregiver_name}}, {{date}}).', null=True),
        ),
    ]
