# Generated by Django 5.1.7 on 2025-07-31 15:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_documenttemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content for the template with formatting and placeholders (e.g., {{caregiver_name}}, {{date}}).', null=True),
        ),
    ]
