# Generated by Django 5.1.7 on 2025-08-20 17:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_documenttemplate_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Raw content of the uploaded file (e.g., Word document text or XML) to preserve original formatting.', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content for the template with formatting and placeholders.', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of placeholders used in the template, e.g., ['{{employee_name}}', '{{date}}'].", null=True),
        ),
    ]
