# Generated by Django 5.1.7 on 2025-08-20 18:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_documenttemplate_raw_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content for the template with formatting and placeholders.', null=True),
        ),
    ]
