# Generated by Django 5.1.7 on 2025-08-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
    ]
