# Generated by Django 5.1.7 on 2025-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='normalized_placeholders',
            field=models.JSONField(blank=True, default=list, help_text="Normalized versions of placeholders, e.g., ['date', 'employee_name'].", null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of original placeholders, e.g., ['[INSERT THE DATE HERE]', '{{employee_name}}'].", null=True),
        ),
    ]
