# Generated by Django 5.1.7 on 2025-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_documenttemplate_normalized_placeholders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='normalized_placeholders',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of placeholders used in the template, e.g., ['{{employee_name}}', '{{date}}'].", null=True),
        ),
    ]
