# Generated by Django 5.1.7 on 2025-08-21 09:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_remove_documenttemplate_normalized_placeholders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='raw_content',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text content for the template with formatting and placeholders (e.g., {{caregiver_name}}, {{date}}).', null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text="List of placeholders used in the template, e.g. ['{{employee_name}}', '{{date}}']", null=True),
        ),
    ]
