# Generated by Django 5.1.7 on 2025-09-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_document_created_by_document_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate'),
        ),
    ]
