# Generated by Django 5.1.7 on 2025-09-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_alter_document_document_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype'),
        ),
    ]
