# Generated by Django 5.1.7 on 2025-09-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_documenttemplate_document_type'),
        ('institution', '0047_institution_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
