# Generated by Django 5.1.7 on 2025-06-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_userbranch_unique_default_branch_per_user'),
        ('payroll', '0002_deductiontype_payrollperiod_payslip_payslipitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetype',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_types', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_types', to='institution.institution'),
            preserve_default=False,
        ),
    ]
