# Generated by Django 5.1.7 on 2025-06-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollperiod_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancetype',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='deductiontype',
            name='institution',
        ),
    ]
