# Generated by Django 5.1.7 on 2025-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollperiod_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
