# Generated by Django 5.1.7 on 2025-06-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_remove_allowancetype_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='institution',
        ),
    ]
