# Generated by Django 5.1.7 on 2025-06-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_allowancetype_name_alter_deductiontype_name'),
        ('payroll', '0007_allowancetype_institution_deductiontype_institution_and_more'),
    ]

    operations = [
    ]
