# Generated by Django 5.1.7 on 2025-07-21 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_merge_20250630_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeededuction',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
