# Generated by Django 5.1.7 on 2025-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_employeeallowance_effective_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetype',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], help_text='Frequency of the allowance/deduction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], help_text='Frequency of the allowance/deduction', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
