# Generated by Django 5.1.7 on 2025-08-06 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_allowancetype_frequency_allowancetype_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
