# Generated by Django 5.1.7 on 2025-08-06 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_employeeallowance_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeededuction',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
