# Generated by Django 5.1.7 on 2025-08-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_alter_institutionworkingdays_days'),
        ('payroll', '0012_alter_employeededuction_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='The institution this tax type belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tax_types', to='institution.institution')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('institution', 'name')},
            },
        ),
    ]
