# Generated by Django 5.1.7 on 2025-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_employeededuction_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='non_taxable_allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='taxable_allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
