# Generated by Django 5.1.7 on 2025-08-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_taxrule_taxtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxRule',
        ),
        migrations.DeleteModel(
            name='TaxType',
        ),
    ]
