# Generated by Django 5.1.7 on 2025-08-07 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employeeworkingdays'),
        ('institution', '0021_alter_institutiontax_created_by_and_more'),
        ('payroll', '0014_delete_taxrule_delete_taxtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='employee.employee')),
                ('institution_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institutiontax')),
            ],
            options={
                'unique_together': {('employee', 'institution_tax')},
            },
        ),
    ]
