# Generated by Django 5.1.7 on 2025-08-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_payslip_non_taxable_allowances_and_more'),
        ('payroll', '0015_employeetax'),
    ]

    operations = [
    ]
