# Generated by Django 5.1.7 on 2025-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_employeetax'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetax',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
