# Generated by Django 5.1.7 on 2025-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_employeetax_is_active_payrollperiod_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancetype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deductiontype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeededuction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeetax',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='is_active',
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeetax',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetax',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
