# Generated by Django 5.1.7 on 2025-08-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employee_options_remove_employee_is_active_and_more'),
        ('institution', '0023_remove_branch_is_active_remove_department_is_active_and_more'),
        ('payroll', '0017_remove_allowancetype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeallowance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeededuction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeetax',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employeeallowance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'allowance_type'), name='unique_active_allowance_type_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeededuction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'deduction_type'), name='unique_active_deduction_type_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeetax',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'institution_tax'), name='unique_active_institution_tax_per_employee'),
        ),
    ]
