# Generated by Django 5.1.7 on 2025-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employee_options_remove_employee_is_active_and_more'),
        ('payroll', '0018_alter_employeeallowance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'payroll_period'), name='unique_active_payroll_period_per_employee'),
        ),
    ]
