# Generated by Django 5.1.7 on 2025-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_merge_20250808_0935'),
        ('payroll', '0020_allowancetype_is_active_deductiontype_is_active_and_more'),
    ]

    operations = [
    ]
