# Generated by Django 5.1.7 on 2025-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_merge_20250812_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductiontype',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('late', 'Lateness'), ('absentism', 'Absentism')], help_text='If set, deduction is applied when employee attendance check matches this condition', max_length=100, null=True),
        ),
    ]
