# Generated by Django 5.1.7 on 2025-08-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_deductiontype_attendance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deductiontype',
            old_name='attendance_type',
            new_name='attendance_penalty_for',
        ),
    ]
