# Generated by Django 5.1.7 on 2025-08-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_rename_attendance_type_deductiontype_attendance_penalty_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductiontype',
            name='attendance_penalty_for',
        ),
    ]
