# Generated by Django 5.1.7 on 2025-08-29 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_employeeattendance_attendance_status_and_more'),
        ('payroll', '0024_remove_deductiontype_attendance_penalty_for'),
        ('spotcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('penalty_type', models.CharField(choices=[('late_coming', 'Late Coming'), ('early_leaving', 'Early Leaving'), ('absent', 'Absent'), ('no_response_spotcheck', 'No Response for Spotcheck'), ('late_spotcheck_response', 'Late Spotcheck Response')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waived', 'Waived'), ('applied', 'Applied')], default='applied', max_length=50)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='employee.employeeattendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='employee.employee')),
                ('spot_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='spotcheck.employeespotcheck')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
