# Generated by Django 5.1.7 on 2025-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_employeepenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_penalties',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
