# Generated by Django 5.1.7 on 2025-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_payslip_total_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetype',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepenalty',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='employeetax',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
