# Generated by Django 5.1.7 on 2025-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_allowancetype_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='taxable_gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
