# Generated by Django 5.1.7 on 2025-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_payslip_taxable_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepenalty',
            name='pending_waive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepenalty',
            name='waive_request_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
