
# Generated by Django 5.1.7 on 2025-09-03 12:27



import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_employeepenalty_pending_waive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepenalty',
            name='pending_waive',
        ),
        migrations.RemoveField(
            model_name='employeepenalty',
            name='waive_request_notes',
        ),
        migrations.CreateModel(
            name='PenaltyWaiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('reason', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiverequests', to='payroll.employeepenalty')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
