# Generated by Django 5.1.7 on 2025-10-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_allowancetype_created_by_allowancetype_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payslip',
            name='unique_active_payroll_period_per_employee',
        ),
    ]
