# Generated by Django 5.1.7 on 2025-10-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_remove_payslip_unique_active_payroll_period_per_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepenalty',
            name='status',
            field=models.CharField(choices=[('waived', 'Waived'), ('applied', 'Applied'), ('system_cancelled', 'System Cancelled')], default='applied', max_length=50),
        ),
    ]
