# Generated by Django 5.1.7 on 2025-06-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('employee', '0008_employeeattendance_overtime_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disciplines', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_disciplines', to='employee.employee'),
        ),
    ]
