# Generated by Django 5.1.7 on 2025-08-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_alter_disciplinaryaction_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
