# Generated by Django 5.1.7 on 2025-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_disciplinaryaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
