# Generated by Django 5.1.7 on 2025-06-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_first_name_remove_employee_last_name'),
        ('employee', '0003_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
    ]
