# Generated by Django 5.1.7 on 2025-06-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeetype_worktype_employee_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
