# Generated by Django 5.1.7 on 2025-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
