# Generated by Django 5.1.7 on 2025-06-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_merge_20250620_1237'),
        ('employee', '0008_employeeattendance_overtime_hours'),
    ]

    operations = [
    ]
