# Generated by Django 5.1.7 on 2025-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_merge_20250630_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
