# Generated by Django 5.1.7 on 2025-06-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_merge_20250627_1130'),
        ('employee', '0010_employee_gender'),
    ]

    operations = [
    ]
