# Generated by Django 5.1.7 on 2025-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_merge_0009_merge_20250627_1130_0010_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
