# Generated by Django 5.1.7 on 2025-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeetype_created_at_employeetype_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
