# Generated by Django 5.1.7 on 2025-07-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nssf_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
