# Generated by Django 5.1.7 on 2025-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_salary_overridden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_overridden',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
