# Generated by Django 5.1.7 on 2025-07-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_salary_overridden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary_overridden',
        ),
    ]
