# Generated by Django 5.1.7 on 2025-07-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_contract'),
        ('employee', '0014_employee_nssf_no_employee_tin'),
    ]

    operations = [
    ]
