# Generated by Django 5.1.7 on 2025-07-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_merge_20250725_0903'),
        ('employee', '0016_alter_employee_date_of_joining'),
    ]

    operations = [
    ]
