# Generated by Django 5.1.7 on 2025-07-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0017_merge_20250725_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="user_template",
            field=models.FileField(blank=True, null=True, upload_to="user_templates/"),
        ),
    ]
