# Generated by Django 5.1.7 on 2025-07-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_contract_user_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user_template',
        ),
    ]
