# Generated by Django 5.1.7 on 2025-07-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0018_contract_user_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={},
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_file",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_id",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="user_template",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_reference",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="original_contract",
            field=models.FileField(
                blank=True, null=True, upload_to="contracts/original/"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_contract",
            field=models.FileField(
                blank=True, null=True, upload_to="contracts/signed/"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="employee.employee",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("under_review", "Under Review"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("terminated", "Terminated"),
                ],
                max_length=20,
            ),
        ),
    ]
