# Generated by Django 5.1.7 on 2025-07-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_contract_options_remove_contract_contract_file_and_more'),
        ('recruitment', '0018_jobposition_contract_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('contract_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('original_contract', models.FileField(blank=True, null=True, upload_to='contracts/original/')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='contracts/signed/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_contract', to='recruitment.jobadvertapplication')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employee.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
