# Generated by Django 5.1.7 on 2025-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_employeecontract_delete_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(blank=True, choices=[('MATCHED_NEEDS_REVIEW', 'Matched, Needs Review'), ('NOT_MATCHED_NEEDS_REVIEW', 'Not Matched, Needs Review')], default='PENDING', max_length=30),
        ),
    ]
