# Generated by Django 5.1.7 on 2025-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employeecontract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='differences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
