# Generated by Django 5.1.7 on 2025-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_employeecontract_differences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(blank=True, choices=[('MATCHED_NEEDS_REVIEW', 'Matched, Needs Review'), ('NOT_MATCHED_NEEDS_REVIEW', 'Not Matched, Needs Review'), ('APPROVED', 'Approved')], default='PENDING', max_length=30),
        ),
    ]
