# Generated by Django 5.1.7 on 2025-08-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employeecontract_status'),
        ('settings', '0003_systemday'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.ManyToManyField(help_text="Must be selected from institution's working days", related_name='employee_working_days', to='settings.systemday')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_working_days', to='employee.employee')),
            ],
        ),
    ]
