# Generated by Django 5.1.7 on 2025-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employeeworkingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this EmployeeAttendance should be treated as active or in active.'),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this EmployeeType should be treated as active or in active'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this WorkType should be treated as active or in active.'),
        ),
    ]
