# Generated by Django 5.1.7 on 2025-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employeeworkingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='check_in_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='check_in_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='check_out_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='check_out_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
