# Generated by Django 5.1.7 on 2025-08-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_employeeattendance_check_in_latitude_and_more'),
        ('employee', '0027_employee_is_active_employeeattendance_is_active_and_more'),
    ]

    operations = [
    ]
