# Generated by Django 5.1.7 on 2025-08-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_merge_20250812_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_user',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_email',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_nin',
        ),
        migrations.RemoveConstraint(
            model_name='employeecontract',
            name='unique_active_contract_reference',
        ),
        migrations.RemoveConstraint(
            model_name='employeetype',
            name='unique_active_employee_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='employeetype',
            name='unique_active_employee_type_code',
        ),
        migrations.RemoveConstraint(
            model_name='worktype',
            name='unique_active_work_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='worktype',
            name='unique_active_work_type_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeetype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employeetype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='is_active',
        ),
    ]
