# Generated by Django 5.1.7 on 2025-08-13 08:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_alter_employee_options_and_more'),
        ('institution', '0027_branch_deleted_at_branch_is_active_and_more'),
        ('recruitment', '0024_jobposition_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user',), name='unique_active_employee_user'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_active_employee_email'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nin',), name='unique_active_employee_nin'),
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract_reference',), name='unique_active_contract_reference'),
        ),
        migrations.AddConstraint(
            model_name='employeetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_employee_type_name'),
        ),
        migrations.AddConstraint(
            model_name='employeetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_employee_type_code'),
        ),
        migrations.AddConstraint(
            model_name='worktype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_active_work_type_name'),
        ),
        migrations.AddConstraint(
            model_name='worktype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='unique_active_work_type_code'),
        ),
    ]
