# Generated by Django 5.1.7 on 2025-08-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_employee_options_employee_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'date')},
        ),
    ]
