# Generated by Django 5.1.7 on 2025-08-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_employeeattendance_unique_together'),
        ('institution', '0028_institution_is_attendance_penalties_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AddField(
            model_name='employeeworkingdays',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkingdays',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeworkingdays',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
