# Generated by Django 5.1.7 on 2025-08-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_employeetype_institution_and_more'),
        ('institution', '0028_institution_is_attendance_penalties_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
