# Generated by Django 5.1.7 on 2025-08-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_worktype_institution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeetype',
            name='unique_active_employee_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='employeetype',
            name='unique_active_employee_type_code',
        ),
        migrations.RemoveConstraint(
            model_name='worktype',
            name='unique_active_work_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='worktype',
            name='unique_active_work_type_code',
        ),
    ]
