# Generated by Django 5.1.7 on 2025-08-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_employee_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bank_account_name',
        ),
    ]
