# Generated by Django 5.2 on 2025-08-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0036_remove_employee_bank_account_name"),
        ("institution", "0031_institutionkycdocument_delete_institutiondocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="payroll_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_payroll_employees",
                to="institution.branch",
            ),
        ),
    ]
