# Generated by Django 5.1.7 on 2025-08-29 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_employee_payroll_branch'),
        ('institution', '0031_institutionkycdocument_delete_institutiondocument'),
        ('recruitment', '0033_jobpositionadvert_employee_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_user',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_email',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_nin',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('department', 'user'), name='unique_active_employee_user_per_department_institution'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('department', 'email'), name='unique_active_employee_email_per_department_institution'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('department', 'nin'), name='unique_active_employee_nin_per_department_institution'),
        ),
    ]
