# Generated by Django 5.1.7 on 2025-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_remove_employee_unique_active_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='attendance_status',
            field=models.CharField(choices=[('late', 'Late'), ('early_checkout', 'Early Checkout'), ('overtime', 'Overtime'), ('on_time', 'On Time'), ('absent', 'Absent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='early_checkout_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='late_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
