# Generated by Django 5.2 on 2025-08-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0038_remove_employee_unique_active_employee_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeWorkingDays",
        ),
    ]
