# Generated by Django 5.2 on 2025-08-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0039_delete_employeeworkingdays"),
        ("settings", "0006_systemconfiguration_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.systemday",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeWorkingDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "days",
                    models.ManyToManyField(
                        help_text="Must be selected from institution's working days",
                        related_name="employee_working_days",
                        through="employee.EmployeeDay",
                        to="settings.systemday",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_working_days",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="employeeday",
            name="employee_working_days",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_days",
                to="employee.employeeworkingdays",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeday",
            unique_together={("employee_working_days", "day")},
        ),
    ]
