# Generated by Django 5.1.7 on 2025-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_alter_employeeattendance_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='early_checkout_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
