# Generated by Django 5.1.7 on 2025-08-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_alter_employeeattendance_early_checkout_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_status',
            field=models.CharField(choices=[('late', 'Late'), ('early_checkout', 'Early Checkout'), ('overtime', 'Overtime'), ('on_time', 'On Time'), ('absent', 'Absent'), ('pending', 'Pending')], max_length=20),
        ),
    ]
