# Generated by Django 5.1.7 on 2025-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_alter_employeeattendance_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_status',
            field=models.CharField(choices=[('late', 'Late'), ('early_checkout', 'Early Checkout'), ('overtime', 'Overtime'), ('on_time', 'On Time'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
