# Generated by Django 5.1.7 on 2025-08-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_employeeshift'),
        ('employee', '0043_alter_employeeattendance_attendance_status'),
    ]

    operations = [
    ]
