# Generated by Django 5.1.7 on 2025-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_employee_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeday',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeeday',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
