# Generated by Django 5.1.7 on 2025-08-31 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_employee_approval_status_and_more'),
        ('institution', '0039_alter_department_institution'),
        ('settings', '0006_systemconfiguration_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.systemday'),
        ),
        migrations.AlterField(
            model_name='employeeday',
            name='employee_working_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_days', to='employee.employeeworkingdays'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_shift', to='institution.branchshift'),
        ),
        migrations.AlterField(
            model_name='employeeworkingdays',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_working_days', to='employee.employee'),
        ),
    ]
