# Generated by Django 5.1.7 on 2025-08-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0046_alter_employeeattendance_employee_and_more'),
        ('employee', '0046_alter_employeeday_end_time_and_more'),
    ]

    operations = [
    ]
