# Generated by Django 5.1.7 on 2025-09-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_merge_20250831_1351'),
        ('institution', '0041_branchpenaltyconfig_unique_branch_penalty_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift', to='institution.branchshift'),
        ),
    ]
