# Generated by Django 5.1.7 on 2025-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_alter_employeeshift_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_user_per_department_institution',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_email_per_department_institution',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_active_employee_nin_per_department_institution',
        ),
    ]
