# Generated by Django 5.1.7 on 2025-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0049_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_status',
            field=models.CharField(choices=[('late', 'Late'), ('early_checkout', 'Early Checkout'), ('overtime', 'Overtime'), ('on_time', 'On Time'), ('absent', 'Absent'), ('late_and_early', 'Late and Early Checkout'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
