# Generated by Django 5.1.7 on 2025-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0052_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='worked_hours',
            field=models.IntegerField(default=0),
        ),
    ]
