# Generated by Django 5.1.7 on 2025-09-02 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_employeeattendance_worked_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyHourAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_worked_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_late_minutes', models.PositiveIntegerField(default=0)),
                ('total_early_checkout_minutes', models.PositiveIntegerField(default=0)),
                ('total_absent_days', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_hour_accounts', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Monthly Hour Account',
                'verbose_name_plural': 'Employee Monthly Hour Accounts',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
