# Generated by Django 5.1.7 on 2025-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0054_employeemonthlyhouraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
