# Generated by Django 5.1.7 on 2025-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0055_alter_employeeday_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
