# Generated by Django 5.1.7 on 2025-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0056_alter_employeeday_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__fullname'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
