# Generated by Django 5.1.7 on 2025-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_qualificationaward_remove_employee_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='reason_of_leaving',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
