# Generated by Django 5.1.7 on 2025-09-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_qualificationaward_remove_employee_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='award',
        ),
        migrations.RemoveField(
            model_name='education',
            name='qualification',
        ),
    ]
