# Generated by Django 5.1.7 on 2025-09-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0059_alter_workexperience_reason_of_leaving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='award',
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='educations', to='employee.qualificationaward'),
        ),
    ]
