# Generated by Django 5.1.7 on 2025-09-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0059_remove_education_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='employee.qualificationaward'),
        ),
    ]
