# Generated by Django 5.1.7 on 2025-09-09 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_remove_education_award_alter_education_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee.qualificationaward'),
        ),
    ]
