# Generated by Django 5.1.7 on 2025-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0061_alter_nextofkin_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='relationship',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('child', 'Child'), ('friend', 'Friend'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=50),
        ),
    ]
