# Generated by Django 5.1.7 on 2025-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0063_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('spouse', 'Spouse'), ('child', 'Child'), ('friend', 'Friend'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=50),
        ),
    ]
