# Generated by Django 5.1.7 on 2025-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0064_alter_nextofkin_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
