# Generated by Django 5.1.7 on 2025-09-17 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0066_child_created_by_child_updated_by_and_more'),
        ('institution', '0043_remove_institution_zoom_account_id_and_more'),
        ('recruitment', '0037_interviewstage_created_by_interviewstage_updated_by_and_more'),
        ('settings', '0008_meetingintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='recruitment.jobposition'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank_accounts', to='institution.institutionbanktype'),
        ),
        migrations.AlterField(
            model_name='employeeday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.systemday'),
        ),
        migrations.AlterField(
            model_name='employeeday',
            name='employee_working_days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_days', to='employee.employeeworkingdays'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shift', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeworkingdays',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_working_days', to='employee.employee'),
        ),
    ]
