# Generated by Django 5.1.7 on 2025-09-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0067_alter_employee_position_alter_employee_user_and_more'),
        ('employee', '0067_employeecompanyemail'),
    ]

    operations = [
    ]
