# Generated by Django 5.1.7 on 2025-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0069_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
