# Generated by Django 5.1.7 on 2025-09-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0070_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompanyemail',
            name='provider',
            field=models.CharField(blank=True, choices=[('cpanel', 'cPanel'), ('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365')], help_text='Email provider (e.g., cPanel, Google Workspace)', max_length=20, null=True),
        ),
    ]
