# Generated by Django 5.1.7 on 2025-09-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0071_alter_employeecompanyemail_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompanyemail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
