# Generated by Django 5.1.7 on 2025-09-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0073_alter_employeecompanyemail_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompanyemail',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_email', to='employee.employee'),
        ),
    ]
