# Generated by Django 5.1.7 on 2025-09-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0074_alter_employeecompanyemail_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('document_type', models.CharField(help_text='Type of document requested (e.g., ID, Certificate, Contract).', max_length=100)),
                ('document_format', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('jpg', 'JPG'), ('any', 'Any'), ('jpeg', 'JPEG'), ('png', 'PNG')], help_text='Format of the document requested (e.g., PDF, Word).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the document request.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due date for submitting the document.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='The user who made the document request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the document request for this employee.', max_length=20)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to='employee.documentrequest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='employees',
            field=models.ManyToManyField(help_text='Employees to whom the document is requested.', related_name='document_requests', through='employee.DocumentRequestEmployee', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='RequestedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('file', models.FileField(help_text='The uploaded document file.', upload_to='employee_documents/')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the document.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL)),
                ('document_request_employee', models.ForeignKey(help_text='The document request and employee this file relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.documentrequestemployee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
