# Generated by Django 5.1.7 on 2025-09-29 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0074_alter_employeecompanyemail_employee'),
        ('institution', '0044_alter_department_institution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecompanyemail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeecompanyemail',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_emails', to='institution.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeecompanyemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='employeecompanyemail',
            unique_together={('institution', 'email')},
        ),
    ]
