# Generated by Django 5.1.7 on 2025-09-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0077_employeemonthlyhouraccount_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeecompanyemail',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeecompanyemail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employeecompanyemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
