# Generated by Django 5.1.7 on 2025-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0078_alter_employeecompanyemail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
