# Generated by Django 5.1.7 on 2025-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0079_alter_employee_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
