# Generated by Django 5.1.7 on 2025-10-13 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0081_employeeelogs'),
        ('institution', '0048_taxrulecategory_code'),
        ('recruitment', '0043_jobposition_reports_to_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBirthdayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['date_of_birth'], name='employee_em_date_of_cb658f_idx'),
        ),
        migrations.AddField(
            model_name='employeebirthdaytask',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
