# Generated by Django 5.1.7 on 2025-10-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_name'),
        ('employee', '0082_employeebirthdaytask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeelogs',
            name='record_data',
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the log event', null=True),
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device from which the log originates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='external_user_id',
            field=models.CharField(blank=True, help_text='External user ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='internal_user_id',
            field=models.CharField(blank=True, help_text='Internal user ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='record_reference',
            field=models.CharField(blank=True, help_text='Unique log record reference', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeelogs',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number', max_length=50, null=True),
        ),
    ]
