# Generated by Django 5.1.7 on 2025-10-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0083_remove_employeeelogs_record_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeelogs',
            name='external_user_id',
        ),
        migrations.RemoveField(
            model_name='employeeelogs',
            name='internal_user_id',
        ),
        migrations.RemoveField(
            model_name='employeeelogs',
            name='serial_number',
        ),
    ]
