# Generated by Django 5.1.7 on 2025-10-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0084_remove_employeeelogs_external_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeelogs',
            old_name='datetime',
            new_name='date',
        ),
    ]
