# Generated by Django 5.1.7 on 2025-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0085_rename_datetime_employeeelogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeelogs',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of the log event', null=True),
        ),
        migrations.AlterField(
            model_name='employeeelogs',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the log event', null=True),
        ),
    ]
