# Generated by Django 5.1.7 on 2025-10-13 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_name'),
        ('employee', '0086_employeeelogs_time_alter_employeeelogs_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeeLogs',
            new_name='EmployeeLogs',
        ),
    ]
