# Generated by Django 5.1.7 on 2025-10-13 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0087_rename_employeeelogs_employeelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
