# Generated by Django 5.1.7 on 2025-10-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0090_alter_employee_phone_number'),
        ('institution', '0052_alter_branchshift_shift_day_ownershiptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='context',
            field=models.CharField(choices=[('REQUEST', 'Request'), ('ALLOCATION', 'Allocation'), ('OVERRIDE', 'Override')], default='REQUEST', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_shifts', to='institution.branchshift'),
        ),
        migrations.AddIndex(
            model_name='employeeshift',
            index=models.Index(fields=['employee', 'date', 'is_recurring'], name='employee_em_employe_848f03_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshift',
            index=models.Index(fields=['employee', 'start_date', 'end_date', 'is_recurring'], name='employee_em_employe_aa3fda_idx'),
        ),
    ]
