# Generated by Django 5.1.7 on 2025-10-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0091_employeeshift_end_date_employeeshift_is_recurring_and_more'),
        ('institution', '0052_alter_branchshift_shift_day_ownershiptransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checkin_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_checkin_employees', to='institution.branch'),
        ),
    ]
