from django.urls import path
from .views import (
    EmployeeAttendanceDetailAPIView,
    EmployeeAttendanceListCreateAPIView,
    EmployeeBranchDetailAPIView,
    EmployeeBranchManagementAPIView,
    EmployeeListAPIView,
    EmployeeDetailAPIView,
    EmployeeCreateAPIView,
    EmployeeTypeDetailAPIView,
    EmployeeTypeListCreateAPIView,
    EmployeeUpdateAPIView,
    EmployeeDeleteAPIView,
    WorkTypeDetailAPIView,
    WorkTypeListCreateAPIView,
    EmployeeTemplateDownloadAPIView,
    EmployeeContractDetailAPIView,
    EmployeeContractListAPIView,
    EmployeeContractApprovalAPIView,
    EmployeeWorkingDaysDetailAPIView,
    ExportAttendanceExcelView,
    AttendanceReportGetView,
    EmployeeShiftDetailView,
    EmployeeShiftListCreateView,
    EmployeeDashboardAPIView,
    AttendanceDashboardAPIView,
    EmployeeExportView,
)

urlpatterns = [
    path(
        "<int:institution_id>/employee/",
        EmployeeListAPIView.as_view(),
        name="employee-list",
    ),
    path("<int:employee_id>/", EmployeeDetailAPIView.as_view(), name="employee-detail"),
    path("create/", EmployeeCreateAPIView.as_view(), name="create-employee"),
    path(
        "<int:employee_id>/update/",
        EmployeeUpdateAPIView.as_view(),
        name="update-employee",
    ),
    path(
        "<int:employee_id>/working-days/",
        EmployeeWorkingDaysDetailAPIView.as_view(),
        name="employee-working-days",
    ),
    path(
        "template/", EmployeeTemplateDownloadAPIView.as_view(), name="employee-template"
    ),
    path(
        "<int:institution_id>/<int:employee_id>/delete/",
        EmployeeDeleteAPIView.as_view(),
        name="delete-employee",
    ),
    path(
        "<int:employee_id>/branches/",
        EmployeeBranchDetailAPIView.as_view(),
        name="employee-branches",
    ),
    path(
        "branches/attach/",
        EmployeeBranchManagementAPIView.as_view(),
        name="attach-employee-branches",
    ),
    path(
        "<int:employee_id>/attendance/",
        EmployeeAttendanceListCreateAPIView.as_view(),
        name="employee-attendance-list",
    ),
    path(
        "attendance/",
        EmployeeAttendanceListCreateAPIView.as_view(),
        name="attendance-list-create",
    ),
    path(
        "attendance/<int:pk>/",
        EmployeeAttendanceDetailAPIView.as_view(),
        name="attendance-detail",
    ),
    path(
        "employee-types/<int:institution_id>/",
        EmployeeTypeListCreateAPIView.as_view(),
        name="employee-type-list-create",
    ),
    path(
        "employee-types/detail/<int:pk>/",
        EmployeeTypeDetailAPIView.as_view(),
        name="employee-type-detail",
    ),
    path(
        "work-types/<int:institution_id>/",
        WorkTypeListCreateAPIView.as_view(),
        name="work-type-list-create",
    ),
    path(
        "work-types/detail/<int:pk>/",
        WorkTypeDetailAPIView.as_view(),
        name="work-type-detail",
    ),
    path(
        "employee-contracts/<int:pk>/",
        EmployeeContractDetailAPIView.as_view(),
        name="employee-contract-detail",
    ),
    path(
        "employee-contracts/",
        EmployeeContractListAPIView.as_view(),
        name="employee-contract-list-create",
    ),
    path(
        "contracts/<int:pk>/approve/",
        EmployeeContractApprovalAPIView.as_view(),
        name="employee-contract-approve",
    ),
    path(
        "attendance2excel/",
        ExportAttendanceExcelView.as_view(),
        name="export-attendance-2-excel",
    ),
    path("attendance-data/", AttendanceReportGetView.as_view(), name="attendance-data"),
    path(
        "employee-shifts/",
        EmployeeShiftListCreateView.as_view(),
        name="employee-shifts-list",
    ),
    path(
        "employee-shifts/detail/<int:pk>/",
        EmployeeShiftDetailView.as_view(),
        name="employee-shifts-detail",
    ),
    path("analytics/", EmployeeDashboardAPIView.as_view(), name="employee-analytics"),
    path(
        "attendance-analytics/",
        AttendanceDashboardAPIView.as_view(),
        name="attendance-analytics",
    ),
    path(
        "export-employee-excel/<int:institution_id>/",
        EmployeeExportView.as_view(),
        name="export-excel",
    ),
]
