# Generated by Django 5.1.7 on 2025-08-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0038_remove_employee_unique_active_employee_user_and_more'),
        ('institution', '0031_institutionkycdocument_delete_institutiondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCheckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_name', models.CharField(max_length=255)),
                ('status_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchSpotCheckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lower_threshold', models.IntegerField(default=0)),
                ('upper_threshold', models.IntegerField(default=3)),
                ('expires_after_minutes', models.IntegerField(default=60)),
                ('late_starts_after_minutes', models.IntegerField(default=10)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='institution.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSpotCheckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lower_threshold', models.IntegerField(default=0)),
                ('upper_threshold', models.IntegerField(default=3)),
                ('expires_after_minutes', models.IntegerField(default=60)),
                ('late_starts_after_minutes', models.IntegerField(default=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionSPotCheckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lower_threshold', models.IntegerField(default=0)),
                ('upper_threshold', models.IntegerField(default=3)),
                ('expires_after_minutes', models.IntegerField(default=60)),
                ('late_starts_after_minutes', models.IntegerField(default=10)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSpotCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotcheck_time', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initiated_by', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spot_checks', to='employee.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_spot_checks', to='spotcheck.spotcheckstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
