# Generated by Django 5.1.7 on 2025-08-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotcheckstatus',
            name='status_code',
        ),
    ]
