# Generated by Django 5.1.7 on 2025-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcheck', '0002_remove_spotcheckstatus_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchspotchecksetting',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='employeespotchecksetting',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='institutionspotchecksetting',
            name='approval_status',
            field=models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20),
        ),
    ]
