# Generated by Django 5.1.7 on 2025-09-12 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotcheck', '0003_branchspotchecksetting_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchspotchecksetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchspotchecksetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeespotchecksetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeespotchecksetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionspotchecksetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionspotchecksetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
