# Generated by Django 5.1.7 on 2025-09-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0067_alter_employee_position_alter_employee_user_and_more'),
        ('institution', '0044_alter_department_institution_and_more'),
        ('spotcheck', '0004_branchspotchecksetting_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchspotchecksetting',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institution.branch'),
        ),
        migrations.AlterField(
            model_name='employeespotcheck',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_checks', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeespotcheck',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_spot_checks', to='spotcheck.spotcheckstatus'),
        ),
        migrations.AlterField(
            model_name='employeespotchecksetting',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='institutionspotchecksetting',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
