export enum MISC_ACTION_TYPES {
  TOGGLE_SIDEBAR = "misc/TOGGLE_SIDEBAR",
      CLOSE_SIDE_BAR="misc/CLOSE_SIDE_BAR",
    OPEN_SIDE_BAR="misc/OPEN_SIDE_BAR",
    SAVE_EMPLOYEE_FORM="misc/SAVE_EMPLOYEE_FORM",
    CLEAR_EMPLOYEE_FORM="misc/CLEAR_EMPLOYEE_FORM"
}
