export enum MISC_ACTION_TYPES {
	TOGGLE_SIDEBAR = "misc/TOGGLE_SIDEBAR",
	CLOSE_SIDE_BAR = "misc/CLOSE_SIDE_BAR",
	OPEN_SIDE_BAR = "misc/OPEN_SIDE_BAR",
	SAVE_EMPLOYEE_FORM = "misc/SAVE_EMPLOYEE_FORM",
	CLEAR_EMPLOYEE_FORM = "misc/CLEAR_EMPLOYEE_FORM",
	SAVE_JOB_ADVERT_FORM = "misc/SAVE_JOB_ADVERT_FORM",
	CLEAR_JOB_ADVERT_FORM = "misc/CLEAR_JOB_ADVERT_FORM",
	SAVE_APPLICATION_FORM = "misc/SAVE_APPLICATION_FORM",
	CLEAR_APPLICATION_FORM = "misc/CLEAR_APPLICATION_FORM",

	CACHE_EMPLOYEES_PAGE = "misc/CACHE_EMPLOYEES_PAGE",
	CLEAR_EMPLOYEES_CACHE = "misc/CLEAR_EMPLOYEES_CACHE",
	SET_EMPLOYEES_CACHE_TIMESTAMP = "misc/SET_EMPLOYEES_CACHE_TIMESTAMP",
	REQUIRE_ANNOUNCEMENT_ACKNOWLDEGMENT_START = "misc/REQUIRE_ANNOUNCEMENT_ACKNOWLDEGMENT_START",
	REQUIRE_ANNOUNCEMENT_ACKNOWLDEGMENT_SUCCESS = "misc/REQUIRE_ANNOUNCEMENT_ACKNOWLDEGMENT_SUCCESS",
	CLEAR_ACKNOWLEDGMENT_REQUIRED_ANNOUNCEMENT = "misc/CLEAR_ACKNOWLEDGMENT_REQUIRED_ANNOUNCEMENT",

	SET_THEME_COLOR = "misc/SET_THEME_COLOR",
	GENERATE_THEME_PALETTE = "misc/GENERATE_THEME_PALETTE",
}
