# Generated by Django 5.2.3 on 2025-06-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'institution')},
        ),
    ]
