# Generated by Django 5.1.7 on 2025-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_systemtype_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
