# Generated by Django 5.1.7 on 2025-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_remove_branch_is_active_remove_department_is_active_and_more'),
        ('users', '0007_permission_is_active_permissioncategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='permissioncategory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='permission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='permission_category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('permission_code',), name='unique_active_permission_code'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('permission_name',), name='unique_active_permission_name'),
        ),
        migrations.AddConstraint(
            model_name='permissioncategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('permission_category_name',), name='unique_active_permission_category_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'institution'), name='unique_active_name_per_institution'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
    ]
