# Generated by Django 5.1.7 on 2025-09-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_approval_status_rolepermission_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
