# Generated by Django 5.1.7 on 2025-09-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0044_alter_department_institution_and_more'),
        ('users', '0012_customuser_created_by_customuser_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
