# Generated by Django 5.1.7 on 2025-10-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_signature_approval_status_signature_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_active_name_per_institution',
        ),
    ]
