# Generated by Django 5.1.7 on 2025-10-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0048_taxrulecategory_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institution associated with this audit log.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['institution', 'timestamp'], name='audit_audit_institu_b792a5_idx'),
        ),
    ]
