# Generated by Django 5.1.7 on 2025-10-20 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_institution_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0052_alter_branchshift_shift_day_ownershiptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user performing the action.', null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_audit_ip_addr_685e3f_idx'),
        ),
    ]
