# Generated by Django 5.1.7 on 2025-10-20 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_ip_address_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0052_alter_branchshift_shift_day_ownershiptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('DOWNLOAD', 'Download')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the object associated with this action, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the object associated with this action, if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_audit_action_86e815_idx'),
        ),
    ]
