# Generated by Django 5.1.7 on 2025-06-18 22:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('institution', '0004_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=1)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_stages', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvertApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(upload_to='applications/resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/cover_letters/')),
                ('application_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('passed', 'Passed')], default='new', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('job_board', 'Job Board'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_advert_applications_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(default=datetime.datetime.now)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_interviews_created', to=settings.AUTH_USER_MODEL)),
                ('interview_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='recruitment.interviewstage')),
                ('job_position_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='recruitment.jobadvertapplication')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contract_template', models.FileField(upload_to='job_positions/contracts/')),
                ('offer_letter_template', models.FileField(upload_to='job_positions/offer_letters/')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='institution.department')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='recruitment.jobposition')),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expiry_date', models.DateTimeField()),
                ('number_of_employees_expected', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverts', to='recruitment.jobposition')),
            ],
        ),
        migrations.AddField(
            model_name='jobadvertapplication',
            name='job_position_advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.jobpositionadvert'),
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='job_position_advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_stages', to='recruitment.jobpositionadvert'),
        ),
    ]
