# Generated by Django 5.1.7 on 2025-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='contract_template',
            field=models.FileField(blank=True, null=True, upload_to='job_positions/contracts/'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='offer_letter_template',
            field=models.FileField(blank=True, null=True, upload_to='job_positions/offer_letters/'),
        ),
    ]
