# Generated by Django 5.1.7 on 2025-06-19 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_jobposition_contract_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='interview_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='interview_type',
            field=models.CharField(choices=[('onlinee', 'Online'), ('in_person', 'In Person')], default='online', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='location',
            field=models.CharField(default='home', max_length=255),
            preserve_default=False,
        ),
    ]
