# Generated by Django 5.1.7 on 2025-06-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_jobinterview_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='interview_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20),
        ),
    ]
