# Generated by Django 5.1.7 on 2025-06-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_jobinterview_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='job_position_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_interviews', to='recruitment.jobadvertapplication'),
        ),
    ]
