# Generated by Django 5.1.7 on 2025-06-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_jobinterview_job_position_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='job_position_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='recruitment.jobadvertapplication'),
        ),
    ]
