# Generated by Django 5.1.7 on 2025-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_employee_id'),
        ('recruitment', '0007_jobposition_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewstage',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='interviewers',
            field=models.ManyToManyField(related_name='interview_stages', to='employee.employee'),
        ),
    ]
