# Generated by Django 5.1.7 on 2025-07-26 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0008_remove_interviewstage_interviewer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobadvertapplication",
            name="recommended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_headhunt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobadvertapplication",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("job_board", "Job Board"),
                    ("social_media", "Social Media"),
                    ("head_hunt", "Head Hunt"),
                    ("other", "Other"),
                ],
                default="website",
                max_length=20,
            ),
        ),
    ]
