# Generated by Django 5.1.7 on 2025-07-26 08:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0010_institution_zoom_account_id_and_more"),
        ("recruitment", "0009_jobadvertapplication_recommended_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposition",
            name="contract_template",
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the contract template", max_length=255
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Upload"),
                            ("docx", "DOCX Upload"),
                            ("richtext", "Rich Text"),
                        ],
                        default="richtext",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload PDF or DOCX file if applicable",
                        null=True,
                        upload_to="contract_templates/files/",
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Rich text content for the contract template (used if template_type is richtext)",
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as default template for the institution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_templates",
                        to="institution.institution",
                    ),
                ),
                (
                    "job_positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Job positions using this template (leave blank for institution-wide default)",
                        related_name="contract_templates",
                        to="recruitment.jobposition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("institution", "is_default"),
                        name="unique_default_template_per_institution",
                    )
                ],
            },
        ),
    ]
