# Generated by Django 5.1.7 on 2025-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_jobadvertapplication_recommended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='job_position_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpositionadvert',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('expired', 'Expired'), ('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='pending_approval', max_length=20),
        ),
    ]
