# Generated by Django 5.1.7 on 2025-07-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0010_remove_jobposition_contract_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Upload"),
                    ("docx", "DOCX Upload"),
                    ("richtext", "Text"),
                ],
                default="richtext",
                max_length=10,
            ),
        ),
    ]
