# Generated by Django 5.1.7 on 2025-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0011_alter_contracttemplate_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="template_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "DOCX"), ("richtext", "Text")],
                default="richtext",
                max_length=10,
            ),
        ),
    ]
