# Generated by Django 5.1.7 on 2025-07-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0010_jobposition_job_position_status_and_more"),
        ("recruitment", "0012_alter_contracttemplate_template_type"),
    ]

    operations = []
