# Generated by Django 5.1.7 on 2025-07-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_jobadvertapplication_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpositionadvert',
            old_name='status',
            new_name='job_position_advert_status',
        ),
    ]
