# Generated by Django 5.1.7 on 2025-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_rename_status_jobpositionadvert_job_position_advert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositionadvert',
            name='advert_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=20),
        ),
    ]
