# Generated by Django 5.1.7 on 2025-07-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_jobpositionadvert_advert_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
    ]
