# Generated by Django 5.1.7 on 2025-07-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document'),
        ('recruitment', '0017_delete_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_positions', to='documents.documenttemplate'),
        ),
    ]
