# Generated by Django 5.1.7 on 2025-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_jobposition_contract_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpositionadvert',
            name='advert_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Internal and External')], default='external', max_length=20),
        ),
    ]
