# Generated by Django 5.1.7 on 2025-07-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0013_alter_institution_default_employee_role'),
        ('recruitment', '0019_alter_jobpositionadvert_advert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_positions', to='institution.department'),
        ),
    ]
