# Generated by Django 5.1.7 on 2025-07-31 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_alter_jobposition_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpositionadvert',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='jobpositionadvert',
            constraint=models.UniqueConstraint(condition=models.Q(('job_position_advert_status', 'active')), fields=('job_position',), name='unique_active_advert_per_job_position'),
        ),
    ]
