# Generated by Django 5.1.7 on 2025-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_alter_jobpositionadvert_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
