# Generated by Django 5.1.7 on 2025-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_jobposition_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='is_active',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
