# Generated by Django 5.1.7 on 2025-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_remove_jobposition_is_active_jobposition_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
