# Generated by Django 5.1.7 on 2025-08-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_requireddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this position', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this position', max_digits=10, null=True),
        ),
    ]
