# Generated by Django 5.1.7 on 2025-08-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_remove_jobposition_salary_jobposition_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstage',
            name='feedback_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
