# Generated by Django 5.1.7 on 2025-08-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_remove_jobposition_salary_jobposition_salary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_position_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
