# Generated by Django 5.1.7 on 2025-08-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_alter_jobposition_job_position_status'),
        ('recruitment', '0027_interviewstage_feedback_fields'),
    ]

    operations = [
    ]
