# Generated by Django 5.1.7 on 2025-08-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0028_merge_20250822_1348'),
        ('recruitment', '0028_merge_20250822_1400'),
    ]

    operations = [
    ]
