# Generated by Django 5.1.7 on 2025-08-23 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0029_merge_20250822_1454"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpositionadvert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobpositionadvert",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpositionadvert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobpositionadvert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
