# Generated by Django 5.1.7 on 2025-08-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0030_jobpositionadvert_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobadvertapplication",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobadvertapplication",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
