# Generated by Django 5.1.7 on 2025-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0031_jobadvertapplication_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobinterview",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobinterview",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
