# Generated by Django 5.1.7 on 2025-08-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_remove_employeetype_unique_active_employee_type_name_and_more'),
        ('recruitment', '0032_jobinterview_deleted_at_jobinterview_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositionadvert',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeetype'),
        ),
        migrations.AddField(
            model_name='jobpositionadvert',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.worktype'),
        ),
    ]
