# Generated by Django 5.1.7 on 2025-08-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0039_alter_department_institution'),
        ('recruitment', '0033_jobpositionadvert_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='institution.department'),
        ),
    ]
