# Generated by Django 5.1.7 on 2025-08-31 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0035_interviewstage_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='interview_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
