# Generated by Django 5.1.7 on 2025-09-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0044_alter_department_institution_and_more'),
        ('recruitment', '0037_interviewstage_created_by_interviewstage_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstage',
            name='job_position_advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_stages', to='recruitment.jobpositionadvert'),
        ),
        migrations.AlterField(
            model_name='jobadvertapplication',
            name='job_position_advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobpositionadvert'),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='interview_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.interviewstage'),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='job_position_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.jobadvertapplication'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='institution.department'),
        ),
        migrations.AlterField(
            model_name='jobpositionadvert',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='recruitment.jobposition'),
        ),
    ]
