# Generated by Django 5.1.7 on 2025-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0039_skillzonecategory_skillzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterview',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
