# Generated by Django 5.1.7 on 2025-10-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0040_alter_jobinterview_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvertapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobadvertapplication',
            name='resume',
        ),
    ]
