# Generated by Django 5.1.7 on 2025-10-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0080_alter_employee_tin'),
        ('recruitment', '0042_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='reports_to_employee',
            field=models.ForeignKey(blank=True, help_text='The specific employee this job position reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_positions', to='employee.employee'),
        ),
    ]
