# Generated by Django 5.1.7 on 2025-10-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_alter_documenttype_institution'),
        ('recruitment', '0043_jobposition_reports_to_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='contract_template',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='offer_letter_template',
        ),
        migrations.CreateModel(
            name='JobPositionDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(choices=[('contract', 'Contract'), ('offer_letter', 'Offer Letter'), ('pip', 'Performance Improvement Plan')], help_text='The purpose of this document template for the job position.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL)),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_position_templates', to='documents.documenttemplate')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_template', to='recruitment.jobposition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
