# Generated by Django 5.1.7 on 2025-10-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_alter_documenttype_institution'),
        ('recruitment', '0044_remove_jobposition_contract_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='document_templates',
            field=models.ManyToManyField(related_name='job_positions', through='recruitment.JobPositionDocumentTemplate', to='documents.documenttemplate'),
        ),
    ]
